In [1]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
os.chdir("C:\\Users\\Abhi's PC\\Downloads\MP3SNGS")

In [3]:
os.getcwd()

"C:\\Users\\Abhi's PC\\Downloads\\MP3SNGS"

In [5]:
classi_data=pd.read_csv("Social_Network_Ads.csv")

In [6]:
classi_data

User ID  Gender  Age  EstimatedSalary  Purchased
0    11021175    Male   42           121315          0
1    17782313    Male   53            67214          0
2    14603818  Female   59           111005          0
3    18188198  Female   39            53414          0
4    19357305    Male   39           114285          0
5    19524602    Male   39           107458          0
6    19455396  Female   20            85582          0
7    16879913  Female   59           148335          1
8    11838352    Male   48            80579          0
9    13118940  Female   42           114204          0
10   19524480  Female   32            87786          0
11   12784093  Female   49           113544          0
12   12895966    Male   55            88300          0
13   14674114    Male   54           147066          0
14   12393248    Male   57           139622          0
15   18842131    Male   41           134716          0
16   11060500    Male   51           116333          1
17   14887406    Male   55            72567          1
18   12606442    Male   44           123254          1
19   17919323  Female   47           113548          1
20   17207101    Male   52            79343          1
21   17159912  Female   20           106149          1
22   10718832    Male   40            59674          1
23   16952550  Female   52            76333          1
24   10494682    Male   28           118742          1
25   16824758    Male   22           105897          1
26   11168323    Male   25           114815          1
27   16945283  Female   38            85428          1
28   13865670    Male   57           114005          0
29   16924204    Male   57           133402          0
..        ...     ...  ...              ...        ...
370  10974769  Female   53            91670          1
371  15997078    Male   39            91484          1
372  15543007  Female   38            79015          0
373  12045512    Male   47           105738          1
374  18148680  Female   60           149376          0
375  19389802  Female   32           132339          1
376  14176702  Female   55            65263          0
377  16272022  Female   43           121151          0
378  13867391    Male   55           143658          1
379  14220159  Female   39           107871          1
380  14988491    Male   35            88727          0
381  13839143    Male   55            78055          1
382  13739543  Female   36            58593          1
383  16476895    Male   27            62004          1
384  16144247  Female   51            99881          1
385  19172097    Male   42            72411          1
386  15679010  Female   47            91721          1
387  12372850    Male   34           140775          0
388  18431004    Male   35            79146          1
389  17054280  Female   58           128623          1
390  18333359    Male   25           128311          1
391  13980301    Male   23            72896          1
392  15750258  Female   57           115969          1
393  19695633    Male   28           111173          1
394  13806266  Female   41           107820          0
395  10220446  Female   20           141231          1
396  12387292    Male   50            75848          1
397  10715173  Female   25            82560          1
398  10016842    Male   55           147667          0
399  11699655  Female   54           134972          1

[400 rows x 5 columns]

In [7]:
len(classi_data)

400

In [8]:
list(classi_data.columns)

['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased']

In [14]:
classi_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB


In [9]:
x=classi_data.iloc[:,2:4]

In [11]:
y=classi_data.iloc[:,-1].values

In [15]:
x

Age  EstimatedSalary
0     42           121315
1     53            67214
2     59           111005
3     39            53414
4     39           114285
5     39           107458
6     20            85582
7     59           148335
8     48            80579
9     42           114204
10    32            87786
11    49           113544
12    55            88300
13    54           147066
14    57           139622
15    41           134716
16    51           116333
17    55            72567
18    44           123254
19    47           113548
20    52            79343
21    20           106149
22    40            59674
23    52            76333
24    28           118742
25    22           105897
26    25           114815
27    38            85428
28    57           114005
29    57           133402
..   ...              ...
370   53            91670
371   39            91484
372   38            79015
373   47           105738
374   60           149376
375   32           132339
376   55            65263
377   43           121151
378   55           143658
379   39           107871
380   35            88727
381   55            78055
382   36            58593
383   27            62004
384   51            99881
385   42            72411
386   47            91721
387   34           140775
388   35            79146
389   58           128623
390   25           128311
391   23            72896
392   57           115969
393   28           111173
394   41           107820
395   20           141231
396   50            75848
397   25            82560
398   55           147667
399   54           134972

[400 rows x 2 columns]

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

D:\an\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
D:\an\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [103]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [104]:
len(x_train)

320

In [105]:
len(y_test)

80

In [106]:
# logistic regression

In [107]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(x_train,y_train)


D:\an\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [108]:
y_pred_log=log_reg.predict(x_test)

In [109]:
y_pred_log

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [110]:
# Nearestneighbors

In [111]:
from sklearn.neighbors import NearestNeighbors
classi_knn=NearestNeighbors(n_neighbors=20,metric='minkowski',p=2)
classi_knn.fit(x_train,y_train)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=None, n_neighbors=20, p=2, radius=1.0)

In [112]:
np.sqrt(400)

20.0

In [1]:
y_pred_nb=classi_knn.prdict(x_test)

NameError: name 'classi_knn' is not defined

In [114]:
# naive bayes

In [115]:
from sklearn.naive_bayes import GaussianNB
classi_nb=GaussianNB()
classi_nb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [116]:
y_pred_nb=classi_nb.predict(x_test)

In [117]:
y_pred_nb

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [118]:
# support vector machine(linear)

In [119]:
from sklearn.svm import SVC
classi_svm_lin=SVC(kernel='linear')
classi_svm_lin.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [120]:
y_pred_lin=classi_svm_lin.predict(x_test)

In [121]:
y_pred_lin

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [122]:
#support vector machine(sigmoid)

In [123]:
from sklearn.svm import SVC
classi_svm_sig=SVC(kernel='sigmoid')
classi_svm_sig.fit(x_train,y_train)

D:\an\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [124]:
y_pred_sig=classi_svm_sig.predict(x_test)

In [125]:
y_pred_sig

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [126]:
# support vector machine(radial basic function)

In [127]:
from sklearn.svm import SVC
classi_svm_rbf=SVC(kernel='rbf')
classi_svm_rbf.fit(x_train,y_train)

D:\an\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [128]:
y_pred_rbf=classi_svm_rbf.predict(x_test)

In [129]:
y_pred_rbf

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [130]:
#SUPPORT VECTOR MACHINE (ploynomial)

In [131]:
from sklearn.svm import SVC
classi_svm_poly=SVC(kernel='poly')
classi_svm_poly.fit(x_train,y_train)

D:\an\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [132]:
y_pred_poly=classi_svm_poly.predict(x_test)

In [133]:
y_pred_poly

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [134]:
# decision tree

In [135]:
from sklearn.tree import DecisionTreeClassifier
classi_dt=DecisionTreeClassifier(criterion='entropy')
classi_dt.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [136]:
y_pred_df=classi_dt.predict(x_test)

In [137]:
y_pred_df

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [138]:
# random forest

In [139]:
from sklearn.ensemble import RandomForestClassifier
classi_rf=RandomForestClassifier(n_estimators=2,criterion='entropy')
classi_rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=2, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [140]:
y_pred_rf=classi_rf.predict(x_test)

In [141]:
y_pred_rf

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [142]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_log)

In [143]:
cm

array([[54,  0],
       [26,  0]], dtype=int64)

In [144]:
(54+0)/80

0.675

In [145]:
(cm[0,0]+cm[1,1])/(cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1])

0.675

In [146]:
confusion_matrix(y_test,y_pred_nb)

array([[54,  0],
       [26,  0]], dtype=int64)

In [151]:
(54+0)/80

0.675

In [148]:
confusion_matrix(y_test,y_pred_lin)

array([[54,  0],
       [26,  0]], dtype=int64)

In [152]:
(54+0)/80

0.675

In [153]:
confusion_matrix(y_test,y_pred_sig)

array([[39, 15],
       [18,  8]], dtype=int64)

In [154]:
(39+8)/80

0.5875

In [155]:
confusion_matrix(y_test,y_pred_rbf)

array([[54,  0],
       [26,  0]], dtype=int64)

In [156]:
(54+0)/80

0.675

In [157]:
confusion_matrix(y_test,y_pred_poly)

array([[54,  0],
       [26,  0]], dtype=int64)

In [158]:
(54)/80

0.675

In [159]:
confusion_matrix(y_test,y_pred_df)

array([[30, 24],
       [12, 14]], dtype=int64)

In [160]:
(30+14)/80

0.55

In [161]:
confusion_matrix(y_test,y_pred_rf)

array([[43, 11],
       [23,  3]], dtype=int64)

In [162]:
(43+3)/80

0.575